services:
  kratos_postgres:
    image: postgres:16
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${DATABASE_USER}",
          "-d",
          "${DATABASE_PASSWORD}",
        ]
      interval: 1s
      timeout: 5s
      retries: 10
    env_file: ./.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: caster
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    networks:
      - caster
    command: bash -c "chmod +x /docker-entrypoint-initdb.d/init-multiple-databases.sh && docker-entrypoint.sh postgres"

  caster_kratos_migrate:
    image: oryd/kratos:v1.2.0
    env_file: ./.env
    environment:
      - DSN=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@kratos_postgres:5432/${DATABASE_NAME}?sslmode=disable
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS=${SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS}
      - SECRETS_CIPHER=${SECRETS_CIPHER}
      - SECRETS_COOKIE=${SECRETS_COOKIE}
      - SERVE_PUBLIC_BASE_URL=${SERVE_PUBLIC_BASE_URL}
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - caster
    depends_on:
      - kratos_postgres

  caster_kratos:
    depends_on:
      - caster_kratos_migrate
    image: oryd/kratos:v1.2.0
    expose:
      - "4433"
      - "4434"
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DSN=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@kratos_postgres:5432/${DATABASE_NAME}?sslmode=disable
      - LOG_LEVEL=info
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS=${SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS}
      - SECRETS_CIPHER=${SECRETS_CIPHER}
      - SECRETS_COOKIE=${SECRETS_COOKIE}
      - SERVE_PUBLIC_BASE_URL=${SERVE_PUBLIC_BASE_URL}
    command: serve -c /etc/config/kratos/kratos.yml
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - caster

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - caster_kratos
      - migrate
    expose:
      - "8084"
    env_file: ./.env
    environment:
      - GIN_MODE=release
      - DSN=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@kratos_postgres:5432/caster?sslmode=disable
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - NEYNAR_API_KEY=${NEYNAR_API_KEY}
      - BASE_URL=${BASE_URL}
    networks:
      - caster

  migrate:
    image: migrate/migrate
    networks:
      - caster
    volumes:
      - type: bind
        source: ./migrations
        target: /etc/billing/migrations
    command:
      [
        "-path",
        "/etc/billing/migrations",
        "-database",
        "postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@kratos_postgres:5432/caster?sslmode=disable",
        "up",
      ]
    links:
      - kratos_postgres
    depends_on:
      - kratos_postgres

  nginx:
    image: nginx:latest
    ports:
      - "8443:443" # Kratos public port
      - "8444:444" # Kratos admin port
      - "8445:445" # API port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - caster_kratos
      - api
    networks:
      - caster
networks:
  caster:
    driver: bridge

volumes:
  postgres-data:
