version: "3.7"
services:
  kratos_postgres:
    image: postgres:16
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${DATABASE_USER}",
          "-d",
          "${DATABASE_PASSWORD}",
        ]
      interval: 1s
      timeout: 5s
      retries: 10
    env_file: ./.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - caster

  caster_kratos_migrate:
    image: oryd/kratos:v1.2.0
    env_file: ./.env
    environment:
      - DSN=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@kratos_postgres:5432/${DATABASE_NAME}?sslmode=disable
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - caster
    depends_on:
      - kratos_postgres

  caster_kratos:
    depends_on:
      - caster_kratos_migrate
    image: oryd/kratos:v1.2.0
    ports:
      - "4433:4433"
      - "4434:4434"
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DSN=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@kratos_postgres:5432/${DATABASE_NAME}?sslmode=disable
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - caster

  caster_mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - caster

  caster:
    build:
      context: .
      dockerfile: ./caster/Dockerfile
    depends_on:
      - caster_kratos
    ports:
      - "8083:8083"
    environment:
      - GIN_MODE=release
    # volumes:
    #   - .:/app
    networks:
      - caster

networks:
  caster:
    driver: bridge

volumes:
  postgres-data:
