name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Setup files
        run: |
          touch backend/.env
          echo "${{ secrets.ENV}}" | base64 -d > backend/.env

      - name: Copy files to droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: root
          password: ${{ secrets.SSH_STAGING_PASSWORD }}
          source: "backend/*"
          target: "/root/sample"
          strip_components: 1

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: root
          password: ${{ secrets.SSH_STAGING_PASSWORD }}
          script: |
            cd /root/sample
            make down
            make up
            max_attempts=30
            attempt=0
            while [ $attempt -lt $max_attempts ]; do
              if docker ps --filter "status=running" --format "table {{.Names}}\t{{.Status}}" | grep "(healthy)"; then
                echo "All containers are up and healthy!"
                exit 0
              else
                echo "Waiting for containers to be up and healthy... (Attempt $((attempt+1))/$max_attempts)"
                sleep 10
                attempt=$((attempt+1))
              fi
            done
            echo "Deployment failed: Containers did not become healthy within the allocated time."
            exit 1
